React-select requires react-input-autosize 1.1.0
Error: Can't resolve 'create-react-class' in '../node_modules/react-input-autosize/lib'
https://github.com/JedWatson/react-select/issues/1694

[#138111477]